// config/config.ts

export const FILTER_TAGS: string[] = [
  "Barter",
  "Provisions",
  "Containers",
  // "Weapon_parts",
  // "Backpacks",
  // "Special_scopes",
];

export const IGNORED_ITEMS: string[] = [
  "Metal fuel tank (0/100)",
  "Expeditionary fuel tank (0/60)",
  "Aquamari water bottle with filter",
  "FP-100 filter absorber",
  "Dogtag USEC",
  "Dogtag BEAR",
  "40mm VOG-25 grenade (GP-25 ammo)",
  "Roubles",
  "Dollars",
  "Euros",
  "GP coin",
  "MS2000 Marker",
  "Leatherman Multitool",
  "Tripwire installation kit",
  "Vortes Ranger 1500 rangefinder",
  "Digital secure DSP radio transmitter",
  "The Eye mortar strike signaling device",
  "Mark of the unheard",
  "Radar station spare parts",
  "GARY ZONT portable electronic warfare device",
  "Sacred Amulet",
  "WI-FI Camera",
  "Signal Jammer",
  "EYE MK2 professional hand-held compass",
  "KOSA UAV electronic jamming device",
  "RSP-30 reactive signal cartirdge (Blue)",
  "RSP-30 reactive signal cartridge (Special Yellow)",
  "M60E6 (FDE)",
  "M60E6",
  "M60E4",
  "SR-3M",
  "Desert Eagle L5 .357",
  "Desert Eagle L5 .50 AE",
  "Desert Eagle L6 .50 AE",
  "Desert Eagle L6 .50 AE WTS",
  "Desert Deagle Mk XIX .50 AE",
  "UZI 9x19 submachine gun",
  "UZI PRO SMG 9x19 submachine gun",
  "UZI PRO Pistol 9x19 submachine gun",
  "Sealed box",
  "Contraband box",
  "Locked case",
  "Case key",
  "Special 40-degree fuel",
  "RSP-30 reactive signal cartridge (Firework)",
  "Jar of pickles",
  "Olivier salad box",
  "SHYSHKA Christmas tree life extender",
  "Saiko TRG M10",
  "Christmas gift",
  "Small Christmas gift",
  "Takedown sling backpack (MultiCam)",
  "Takedown sling backpack (Black)",
  "Blackjack 50",
  "Pilgrim",
  "Attack 2",
  "6SH118 raid backpack",
  "Mystery Ranch SATL",
  "F4 Terminator",
  "Gunslinger II",
  "RUSH 100",
  "Santa's Bag",
];
