// export const ALL_ITEM_CATEGORIES = [
//   "Barter item",
//   "Food and drink",
//   "Weapon mod",
//   "Special item",
//   "info",
//   // ALL CATEGORIES FROM API //TODO: Check if the categories are correct
//   "Equipment",
//   "Armored equipment",
//   "Stackable item",
//   "Weapon",
//   // "Cylinder Magazine",
//   // "Functional mod",
//   // "Essential mod",
//   "Gear mod",
//   "Magazine",
//   "Lubricant",
//   "Compound item",
//   "Meds",
//   "Key",
//   "Item",
//   // "Searchable item",
//   "Muzzle device",
//   "Sights",
//   "Special scope",
// ];

// Default categories to exclude
export const DEFAULT_EXCLUDED_CATEGORIES = new Set([
  "Weapon",
  "Ammo",
  "Ammo container",
  "Key",
]);

export const ALL_ITEM_CATEGORIES = [
  "Assault rifle",
  "Weapon",
  "Compound item",
  "Item",
  "Ammo container",
  "Stackable item",
  "Mechanical Key",
  "Key",
  "Handgun",
  "Throwable weapon",
  "Magazine",
  "Gear mod",
  "Weapon mod",
  "Drink",
  "Food and drink",
  "Food",
  "Money",
  "Comb.tact.device",
  "Functional mod",
  "Knife",
  "Shotgun",
  "Port.container",
  "Searchable item",
  "Flashhider",
  "Muzzle device",
  "Assault scope",
  "Sights",
  "Chest rig",
  "Backpack",
  "Medical item",
  "Meds",
  "Drug",
  "Medikit",
  "Multitools",
  "Special item",
  "Ammo",
  "Armor",
  "Armored equipment",
  "Equipment",
  "Vis.observ.device",
  "Barrel",
  "Essential mod",
  "Sniper rifle",
  "Reflex sight",
  "Pistol grip",
  "Foregrip",
  "Receiver",
  "Charging handle",
  "Handguard",
  "Mount",
  "Stock",
  "Ironsight",
  "Silencer",
  "Comb.muzzle device",
  "Auxiliary Mod",
  "Headwear",
  "Headphones",
  "Locking container",
  "Battery",
  "Barter item",
  "Electronics",
  "Lubricant",
  "Scope",
  "Bipod",
  "Gas block",
  "Night Vision",
  "Special scope",
  "Face Cover",
  "Jewelry",
  "Other",
  "Building material",
  "Household goods",
  "Assault carbine",
  "Map",
  "Compact reflex sight",
  "Marksman rifle",
  "Common container",
  "SMG",
  "Flashlight",
  "Tool",
  "Info",
  "Repair Kits",
  "Medical supplies",
  "Arm Band",
  "Machinegun",
  "Stimulant",
  "Thermal Vision",
  "Keycard",
  "Fuel",
  "Grenade launcher",
  "Compass",
  "Revolver",
  "Cylinder Magazine",
  "Portable Range Finder",
  "Spring Driven Cylinder",
  "UBGL",
  "Radio Transmitter",
  "Random Loot Container",
  "Armor Plate",
  "Cultist Amulet",
  "Mark of the Unheard",
  "Planting Kits",
  "Flyer",
];
