// Default categories to exclude
export const DEFAULT_EXCLUDED_CATEGORIES = new Set([
  "Ammo container",
  "Ammo",
  "Armor",
  "Armor Plate",
  "Armored equipment",
  "Chest rig",
  "Flyer",
  "Key",
  "Repair Kits",
  "Weapon",
]);

export const ALL_ITEM_CATEGORIES = [
  "Ammo container",
  "Ammo",
  "Arm Band",
  "Armor Plate",
  "Armor",
  "Armored equipment",
  "Assault carbine",
  "Assault rifle",
  "Assault scope",
  "Auxiliary Mod",
  "Backpack",
  "Barrel",
  "Barter item",
  "Battery",
  "Bipod",
  "Building material",
  "Charging handle",
  "Chest rig",
  "Comb.muzzle device",
  "Comb.tact.device",
  "Common container",
  "Compact reflex sight",
  "Compass",
  "Compound item",
  "Cultist Amulet",
  "Cylinder Magazine",
  "Drink",
  "Drug",
  "Electronics",
  "Equipment",
  "Essential mod",
  "Face Cover",
  "Flashhider",
  "Flashlight",
  "Flyer",
  "Food and drink",
  "Food",
  "Foregrip",
  "Fuel",
  "Functional mod",
  "Gas block",
  "Gear mod",
  "Grenade launcher",
  "Handguard",
  "Handgun",
  "Headphones",
  "Headwear",
  "Household goods",
  "Info",
  "Ironsight",
  "Item",
  "Jewelry",
  "Key",
  "Keycard",
  "Knife",
  "Locking container",
  "Lubricant",
  "Machinegun",
  "Magazine",
  "Map",
  "Mark of the Unheard",
  "Marksman rifle",
  "Mechanical Key",
  "Medical item",
  "Medical supplies",
  "Medikit",
  "Meds",
  "Money",
  "Mount",
  "Multitools",
  "Muzzle device",
  "Night Vision",
  "Other",
  "Pistol grip",
  "Planting Kits",
  "Port.container",
  "Portable Range Finder",
  "Radio Transmitter",
  "Random Loot Container",
  "Receiver",
  "Reflex sight",
  "Repair Kits",
  "Revolver",
  "Scope",
  "Searchable item",
  "Shotgun",
  "Sights",
  "Silencer",
  "SMG",
  "Sniper rifle",
  "Special item",
  "Special scope",
  "Spring Driven Cylinder",
  "Stackable item",
  "Stimulant",
  "Stock",
  "Thermal Vision",
  "Throwable weapon",
  "Tool",
  "UBGL",
  "Vis.observ.device",
  "Weapon mod",
  "Weapon",
];
