import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import JSON5 from "json5";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const i18nDir = path.join(__dirname, "..", "config", "i18n");
const outputPath = path.join(__dirname, "..", "config", "i18n.generated.ts");

function toObjectLiteral(value, indentLevel = 0) {
  const indent = "  ".repeat(indentLevel);
  const childIndent = "  ".repeat(indentLevel + 1);

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return `[\n${value
      .map((item) => `${childIndent}${toObjectLiteral(item, indentLevel + 1)}`)
      .join(",\n")}\n${indent}]`;
  }

  if (value && typeof value === "object") {
    const entries = Object.entries(value);
    if (entries.length === 0) return "{}";
    return `{\n${entries
      .map(
        ([key, childValue]) =>
          `${childIndent}${JSON.stringify(key)}: ${toObjectLiteral(childValue, indentLevel + 1)}`
      )
      .join(",\n")}\n${indent}}`;
  }

  return JSON.stringify(value);
}

async function main() {
  const fileNames = (await readdir(i18nDir))
    .filter((fileName) => fileName.endsWith(".json5"))
    .sort();

  const messages = {};

  for (const fileName of fileNames) {
    const language = path.basename(fileName, ".json5");
    const filePath = path.join(i18nDir, fileName);
    const source = await readFile(filePath, "utf8");
    messages[language] = JSON5.parse(source);
  }

  const output = `// AUTO-GENERATED by scripts/generate-i18n.mjs
// Do not edit directly. Update config/i18n/*.json5 and rerun the generator.

export const GENERATED_MESSAGES = ${toObjectLiteral(messages)} as const;
`;

  await writeFile(outputPath, output, "utf8");
  console.log(`Generated ${path.relative(path.join(__dirname, ".."), outputPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
